### ISSUE TITLE
Better name for "model_size" parameter

### ISSUE THREAD

**Issue by lchiquitto** [ASRBench/asrbench#2]
While in most cases it does indicate the size of the model, this value is really the model name. IMO we should rename it to either "model_name"  or just "model".

**Comment by BDu4rTe** [comment]
Tks for the suggestion, i totally agree, i've already implemented it in this [commit](https://github.com/BDu4rTe/tcc-benchmark/commit/6446a57fc76be63f33fa28e6ad8e7452ef2358e0#diff-02dc945e200353cecfde53eb43e84ef7e3d0619d58544d69f769774de2bdf428R30).
