### ISSUE TITLE
Delay model loading

### ISSUE THREAD

**Issue by lchiquitto** [ASRBench/asrbench#6]
We're loading models from all configured providers at startup, using all GPU memory available.

Loading the model should be delayed to just before the provider run, not in the provider's __init__() method.

Each provider should probably implement load_model() and unload_model().

**Comment by BDu4rTe** [comment]
Implement methods in [commit](https://github.com/ASRBench/asrbench/commit/e12e9cb03c5b3eb66169397033e95b142dc32c37)
