### ISSUE TITLE
Normalize numbers

### ISSUE THREAD

**Issue by lchiquitto** [ASRBench/asrbench#7]
While checking the results of our latest tests, I saw that some methods/models output numbers as digits (10, 20, 30) while others output them as text (ten, twenty, thirty). Likewise, our references also might use both formats.

We should normalize references and hypothesis to either digits or text before calculating the metrics.

**Comment by BDu4rTe** [comment]
I added a function to do this normalization, I chose to transform numbers into words, tks for reporting this flaw
